#!/bin/bash
set -ex

mkdir lib
git clone https://github.com/DLab/KaXim.git
cd KaXim
git checkout Develop
cd src/grammar
make
cd -
cd Lib
make all
cp libKaXim.so ~/lib/

cd ../LibDebug
make all
cp libKaXim.so ~/lib/libKaXimDebug.so

cd ../src/bindings
make all
cp *.so ~/lib/

export PATH=~/lib:$PATH
