#!/bin/bash
set -ex

mkdir lib
CPLUS_INCLUDE_PATH="~/lib/:$CPLUS_INCLUDE_PATH" ## for Cpp compiler
export CPLUS_INCLUDE_PATH
#mkdir build_eigen
#git clone https://gitlab.com/libeigen/eigen.git
#cd build_eigen
#cmake ../eigen
#make install
#cd ..

git clone https://github.com/DLab/KaXim.git
cd KaXim
git checkout Develop
cd src/grammar
make
cd -
cd Lib
make all
cp libKaXim.so ~/lib/

cd ../LibDebug
make all
cp libKaXim.so ~/lib/libKaXimDebug.so

cd ../src/bindings
make all
cp *.so ~/lib/

export PATH=~/lib:$PATH
